name: Run Build Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'lingua_franca/version.py'
      - 'test/**'
      - 'examples/**'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'lang_support.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build_tests:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Tools
        run: |
          python -m pip install --upgrade build wheel setuptools pip
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
      - name: Build Source Packages
        run: |
          python setup.py sdist
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel
      - name: Install package
        # TODO: cyclonedx patching https://github.com/pypa/gh-action-pip-audit/issues/46
        run: |
          pip install . cyclonedx-python-lib~=4.0
      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          # Ignore irrelevant Mercurial vulnerability
          # Ignore `requests` and `urllib3` vulnerabilities as they are not used in this package
          ignore-vulns: |
            PYSEC-2023-228
            GHSA-9wx4-h78v-vm56
            GHSA-34jh-p97f-mpxf